### ISSUE TITLE
Verificar Token me Requisições

### ISSUE THREAD

**Issue by esterfrazao** [Shopper-Supply/UMAMI-IA_Front#16]
Sempre que ocorrer uma requisição devemos verificar  se o token ainda está válido, e se ele não estiver devemos alertar o usuário e deslogá-lo

Fazer pra reutilizar.

**Comment by lancao2** [comment]
Fiz uma função que verifica se o usuario esta autenticado, mas a função precisa receber 3 parametros, setAuth, hidenModal e router. 
essa função retorna true se ainda existe token deixando a requisisão fluir, caso contrario ele retorna false travando a requisição e redirecionando o usuario para a tela de login e informando que o token expirou. 

afunção é utilizada junto de um if no inicio de todo subimit.
